language: generic

sudo: required

services:
  - docker

before_install:
  - docker build -t pathas1126/react-test-app -f ./frontend/Dockerfile.dev ./frontend

script:
  - docker run -e CI=true pathas1126/react-test-app yarn test

after_success:
  - docker build -t pathas1126/docker-frontend ./frontend
  - docker build -t pathas1126/docker-backend ./backend
  - docker build -t pathas1126/docker-nginx ./nginx

  - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_ID" --password-stdin

  - docker push pathas1126/docker-frontend
  - docker push pathas1126/docker-backend
  - docker push pathas1126/docker-nginx

deploy:
  provider: elasticbeanstalk
  region: ap-northeast-2
  app: docker-fullstack-app
  env: DockerFullstackApp-env
  bucket_name: elasticbeanstalk-ap-northeast-2-281318957201
  bucket_path: elasticbeanstalk-ap-northeast-2-281318957201
  on:
    branch: master

  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_ACCESS_KEY
